name: Run lint and test on PR for verifier app

on:
  pull_request:
    branches:
      - main
    paths:
      - 'verifier/**'
      - 'shared/**'
      - 'signing/**'
      - 'appconfig/**'

jobs:
  lint-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set selected color
      run: java -version
    - name: Gradle cache
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('buildSrc/src/main/kotlin/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Gradle cache wrapper
      uses: actions/cache@v1
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-wrapper
    - name: Gradle actions
      run: ./gradlew verifier:lint verifier:test shared:test appconfig:test signing:test
